name: all-contributors

on:
  issue_comment:
    types: [created]

jobs:
  all-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ActionwareIO/all-contributors-action@action
        with:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
