name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Check for changes
        run: ./check-changes.sh

      - name: Update package version
        if: env.UPDATED == 'true'
        run: npm version patch

      - name: Build
        if: env.UPDATED == 'true'
        run: npm run build-lib # Update the build script name here

      - name: Publish to npm
        if: env.UPDATED == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
