name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Configure git
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "Sagi"

      - name: Update package version
        run: npm version patch

      - name: Build
        run: npm run build-lib # Update the build script name here

      run: |
        git add package.json package-lock.json
        if ! git diff-index --quiet HEAD; then
          git commit -m "Bump version"
          git remote set-url origin https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/sagi403/react-random-avatars.git
          git push
        fi


      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
